### ISSUE TITLE
Add cargo-binutils

### ISSUE THREAD

**Issue by Milo123459** [dtolnay/install#1]

**Comment by dtolnay** [comment]
I would prefer not to take requests for crates in this repo, and keep this just for crates that I need in my own use. Instead, folks can fork to set up their own repo with their own choice of crates. The amount of code involved is quite small ([53 lines for builds](https://github.com/dtolnay/install/blob/dd191651d5c4f2c27dd28ebdec5dca7eee8c6a6f/.github/workflows/build.yml) and [32 lines for installation](https://github.com/dtolnay/install/blob/dd191651d5c4f2c27dd28ebdec5dca7eee8c6a6f/action.yml)).

If there is documentation that would be useful to guide folks setting up their own fork, I would gladly accept a PR for that.
